# Generated by Django 4.2.15 on 2024-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='listing_images'),
        ),
    ]
