# Generated by Django 4.2.15 on 2024-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ebay_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
