# Generated by Django 4.2.15 on 2024-08-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('category_tree_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EbayCategoryAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_name', models.CharField(max_length=255)),
                ('aspect_data_type', models.CharField(default='STRING', max_length=50)),
                ('aspect_mode', models.CharField(default='REQUIRED', max_length=50)),
                ('aspect_usage', models.CharField(default='RECOMMENDED', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='ebay.ebaycategory')),
            ],
        ),
    ]
