# Generated by Django 4.2.15 on 2024-08-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_apitest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitest',
            old_name='endpoint',
            new_name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='member',
        ),
        migrations.AddField(
            model_name='apitest',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='apitest',
            name='response_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apitest',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
