# Generated by Django 4.2.15 on 2024-08-12 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_ebay_access_token'),
        ('ebay', '0003_rename_endpoint_apitest_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitest',
            name='member',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='api_tests', to='member.member'),
            preserve_default=False,
        ),
    ]
