# Generated by Django 4.2.15 on 2024-08-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0004_apitest_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apitest',
            old_name='api_endpoint',
            new_name='endpoint',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='response_status_code',
        ),
        migrations.AlterField(
            model_name='apitest',
            name='request_body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
