# Generated by Django 4.2.15 on 2024-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0005_rename_api_endpoint_apitest_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.TextField()),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField()),
                ('response_body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
